-- Додаємо колонки статистики до mps (рахується як в Excel)
ALTER TABLE mps ADD COLUMN py REAL DEFAULT 0;
ALTER TABLE mps ADD COLUMN pda REAL DEFAULT 0;
ALTER TABLE mps ADD COLUMN vkp REAL DEFAULT 0;
ALTER TABLE mps ADD COLUMN data_sufficient INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN total_votes INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN attended_votes INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN voted_votes INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN total_bills INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN total_laws INTEGER DEFAULT 0;
ALTER TABLE mps ADD COLUMN stats_updated_at TEXT;
